spring:
  application:
    name: encryption
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/student
    username: postgres
    password: root

jwe:
  key-id: student-api-rsa

jwt:
  secret: my-super-secret-local-development-signing-key-please-change-123456
  access-token-expiration-minutes: 15
  refresh-token-expiration-days: 7
